version: "3.8"

services:
  # Demo Web Application
  demo-web:
    build:
      context: ../..
      dockerfile: docker/demo/Dockerfile.web
      args:
        - NODE_ENV=demo
    container_name: freeagentics-demo-web
    ports:
      - "3030:3000" # Demo on port 3030
    environment:
      - NODE_ENV=demo
      - NEXT_PUBLIC_API_URL=http://localhost:3030
      - NEXT_PUBLIC_DEMO_MODE=true
      - NEXT_PUBLIC_DEMO_SPEED=fast
      - DATABASE_URL=postgresql://demo:demo123@demo-db:5432/freeagentics_demo
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - demo-db
      - demo-redis
    networks:
      - demo-network
    restart: unless-stopped

  # Demo Database with Pre-populated Data
  demo-db:
    image: postgres:15-alpine
    container_name: freeagentics-demo-db
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo123
      - POSTGRES_DB=freeagentics_demo
    volumes:
      - demo-db-data:/var/lib/postgresql/data
      - ./init-demo-db.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./seed-demo-data.sql:/docker-entrypoint-initdb.d/02-seed.sql
    ports:
      - "5433:5432" # Different port for demo DB
    networks:
      - demo-network
    restart: unless-stopped

  # Demo Redis for Caching
  demo-redis:
    image: redis:7-alpine
    container_name: freeagentics-demo-redis
    ports:
      - "6380:6379" # Different port for demo Redis
    volumes:
      - demo-redis-data:/data
    networks:
      - demo-network
    restart: unless-stopped

  # Demo Agent Simulator
  demo-simulator:
    build:
      context: ../..
      dockerfile: docker/demo/Dockerfile.simulator
    container_name: freeagentics-demo-simulator
    environment:
      - DEMO_MODE=true
      - SIMULATION_SPEED=10x # 10x speed for demos
      - AUTO_PLAY=true
      - SCENARIO_LOOP=true
      - DATABASE_URL=postgresql://demo:demo123@demo-db:5432/freeagentics_demo
      - REDIS_URL=redis://demo-redis:6379
    depends_on:
      - demo-db
      - demo-redis
    networks:
      - demo-network
    restart: unless-stopped

  # Demo Scenario Runner
  demo-scenarios:
    build:
      context: ../..
      dockerfile: docker/demo/Dockerfile.scenarios
    container_name: freeagentics-demo-scenarios
    environment:
      - RUN_SCENARIOS=explorer_discovery,merchant_trade,scholar_research,guardian_patrol,collaboration
      - SCENARIO_INTERVAL=300 # Run scenarios every 5 minutes
      - DATABASE_URL=postgresql://demo:demo123@demo-db:5432/freeagentics_demo
      - REDIS_URL=redis://demo-redis:6379
    depends_on:
      - demo-db
      - demo-redis
      - demo-simulator
    networks:
      - demo-network
    restart: unless-stopped

  # Nginx for Demo UI Polish
  demo-nginx:
    image: nginx:alpine
    container_name: freeagentics-demo-nginx
    ports:
      - "8080:80" # Main demo entry point
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./demo-assets:/usr/share/nginx/html/assets:ro
    depends_on:
      - demo-web
    networks:
      - demo-network
    restart: unless-stopped

  # Demo Monitoring Dashboard
  demo-monitor:
    build:
      context: ../..
      dockerfile: docker/demo/Dockerfile.monitor
    container_name: freeagentics-demo-monitor
    ports:
      - "3031:3000" # Monitor on port 3031
    environment:
      - DATABASE_URL=postgresql://demo:demo123@demo-db:5432/freeagentics_demo
      - REDIS_URL=redis://demo-redis:6379
    depends_on:
      - demo-db
      - demo-redis
    networks:
      - demo-network
    restart: unless-stopped

networks:
  demo-network:
    driver: bridge
    name: freeagentics-demo

volumes:
  demo-db-data:
  demo-redis-data:
