"""
Active Inference Engine for FreeAgentics

This module implements the Active Inference framework for agent cognition,
including generative models, inference algorithms, and action selection.
"""
from .generative_model import ModelDimensions, ModelParameters, GenerativeModel, DiscreteGenerativeModel, ContinuousGenerativeModel, HierarchicalGenerativeModel, FactorizedGenerativeModel, create_generative_model
from .belief_state import BeliefState, BeliefStateConfig, DiscreteBeliefState, ContinuousBeliefState, create_discrete_belief_state, create_continuous_belief_state, create_belief_state
from .active_inference import InferenceConfig, InferenceAlgorithm, VariationalMessagePassing, BeliefPropagation, GradientDescentInference, NaturalGradientInference, ExpectationMaximization, ParticleFilterInference, create_inference_algorithm
from .precision import PrecisionConfig, PrecisionOptimizer, GradientPrecisionOptimizer, HierarchicalPrecisionOptimizer, MetaLearningPrecisionOptimizer, AdaptivePrecisionController, create_precision_optimizer
from .policy_selection import PolicyConfig, Policy, PolicySelector, DiscreteExpectedFreeEnergy, ContinuousExpectedFreeEnergy, HierarchicalPolicySelector, SophisticatedInference, create_policy_selector
from .temporal_planning import PlanningConfig, TreeNode, TemporalPlanner, MonteCarloTreeSearch, BeamSearchPlanner, AStarPlanner, TrajectorySampling, AdaptiveHorizonPlanner, create_temporal_planner
from .gnn_integration import GNNIntegrationConfig, DirectGraphMapper, LearnedGraphMapper, GNNActiveInferenceAdapter, GraphFeatureAggregator, HierarchicalGraphIntegration, create_gnn_adapter
from .belief_update import BeliefUpdateConfig, DirectGraphObservationModel, LearnedGraphObservationModel, GNNBeliefUpdater, AttentionGraphBeliefUpdater, HierarchicalBeliefUpdater, create_belief_updater
from .hierarchical_inference import HierarchicalConfig, HierarchicalState, HierarchicalLevel, HierarchicalInference, TemporalHierarchicalInference, create_hierarchical_inference
__all__ = ['ModelDimensions', 'ModelParameters', 'GenerativeModel', 'DiscreteGenerativeModel', 'ContinuousGenerativeModel', 'HierarchicalGenerativeModel', 'FactorizedGenerativeModel', 'create_generative_model', 'BeliefState', 'BeliefStateConfig', 'DiscreteBeliefState', 'ContinuousBeliefState', 'create_discrete_belief_state', 'create_continuous_belief_state', 'create_belief_state', 'InferenceConfig', 'InferenceAlgorithm', 'VariationalMessagePassing', 'BeliefPropagation', 'GradientDescentInference', 'NaturalGradientInference', 'ExpectationMaximization', 'ParticleFilterInference', 'create_inference_algorithm', 'PrecisionConfig', 'PrecisionOptimizer', 'GradientPrecisionOptimizer', 'HierarchicalPrecisionOptimizer', 'MetaLearningPrecisionOptimizer', 'AdaptivePrecisionController', 'create_precision_optimizer', 'PolicyConfig', 'Policy', 'PolicySelector', 'DiscreteExpectedFreeEnergy', 'ContinuousExpectedFreeEnergy', 'HierarchicalPolicySelector', 'SophisticatedInference', 'create_policy_selector', 'PlanningConfig', 'TreeNode', 'TemporalPlanner', 'MonteCarloTreeSearch', 'BeamSearchPlanner', 'AStarPlanner', 'TrajectorySampling', 'AdaptiveHorizonPlanner', 'create_temporal_planner', 'GNNIntegrationConfig', 'DirectGraphMapper', 'LearnedGraphMapper', 'GNNActiveInferenceAdapter', 'GraphFeatureAggregator', 'HierarchicalGraphIntegration', 'create_gnn_adapter', 'BeliefUpdateConfig', 'DirectGraphObservationModel', 'LearnedGraphObservationModel', 'GNNBeliefUpdater', 'AttentionGraphBeliefUpdater', 'HierarchicalBeliefUpdater', 'create_belief_updater', 'HierarchicalConfig', 'HierarchicalState', 'HierarchicalLevel', 'HierarchicalInference', 'TemporalHierarchicalInference', 'create_hierarchical_inference']
