import dash
from dash import dcc, html
import plotly.graph_objs as go
from dash.dependencies import Input, Output
import xml.etree.ElementTree as ET
from pathlib import Path
import pandas as pd

# This script creates a web-based dashboard to visualize test results.
# It should be run from the root of the CogniticNet project.
# Example: python3 scripts/testing/test_dashboard.py

# Path to the reports generated by pytest in the CI workflow
JUNIT_REPORT_PATH = Path('./junit-report.xml')
COVERAGE_REPORT_PATH = Path('./coverage.xml')

def parse_junit_report():
    """Parses the JUnit XML report to extract test metrics."""
    if not JUNIT_REPORT_PATH.exists():
        print(f"Warning: JUnit report not found at {JUNIT_REPORT_PATH}")
        return 0, 0, 0, 0.0, []

    try:
        tree = ET.parse(JUNIT_REPORT_PATH)
        root = tree.getroot()
        testsuite = root.find('testsuite')
        if testsuite is None:
            return 0, 0, 0, 0.0, []

        total_tests = int(testsuite.get('tests', 0))
        failures = int(testsuite.get('failures', 0))
        errors = int(testsuite.get('errors', 0))
        total_time = float(testsuite.get('time', 0))

        slowest_tests = []
        for testcase in testsuite.findall('testcase'):
            slowest_tests.append({
                'name': testcase.get('name'),
                'time': float(testcase.get('time', 0))
            })

        slowest_tests.sort(key=lambda x: x['time'], reverse=True)
        return total_tests, failures, errors, total_time, slowest_tests[:10]
    except ET.ParseError as e:
        print(f"Error parsing JUnit report: {e}")
        return 0, 0, 0, 0.0, []

def parse_coverage_report():
    """Parses the Cobertura XML coverage report."""
    if not COVERAGE_REPORT_PATH.exists():
        print(f"Warning: Coverage report not found at {COVERAGE_REPORT_PATH}")
        return 0.0, 0, 0

    try:
        tree = ET.parse(COVERAGE_REPORT_PATH)
        root = tree.getroot()

        line_rate = float(root.get('line-rate', 0)) * 100
        lines_covered = int(root.get('lines-covered', 0))
        lines_valid = int(root.get('lines-valid', 0))

        return line_rate, lines_covered, lines_valid
    except ET.ParseError as e:
        print(f"Error parsing coverage report: {e}")
        return 0.0, 0, 0

# Initialize the Dash app
app = dash.Dash(__name__, external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])
app.title = "Test Dashboard"

# App layout
app.layout = html.Div(style={'fontFamily': 'Arial, sans-serif'}, children=[
    html.H1(children='FreeAgentics - Test Health Dashboard', style={'textAlign': 'center', 'color': '#007BFF'}),

    html.Div(className='row', style={'display': 'flex', 'justifyContent': 'space-around', 'padding': '20px'}, children=[
        html.Div(className='kpi', style={'textAlign': 'center', 'padding': '10px', 'border': '1px solid #ddd', 'borderRadius': '5px'}, children=[
            html.H3('Test Coverage'),
            html.P(id='coverage-indicator', style={'fontSize': 24, 'fontWeight': 'bold', 'color': '#28a745'})
        ]),
        html.Div(className='kpi', style={'textAlign': 'center', 'padding': '10px', 'border': '1px solid #ddd', 'borderRadius': '5px'}, children=[
            html.H3('Tests Passed'),
            html.P(id='tests-passed-indicator', style={'fontSize': 24, 'fontWeight': 'bold', 'color': '#28a745'})
        ]),
        html.Div(className='kpi', style={'textAlign': 'center', 'padding': '10px', 'border': '1px solid #ddd', 'borderRadius': '5px'}, children=[
            html.H3('Total Test Time'),
            html.P(id='test-time-indicator', style={'fontSize': 24, 'fontWeight': 'bold', 'color': '#17a2b8'})
        ])
    ]),

    html.Div(className='row', children=[
        html.Div(className='twelve columns', children=[
            dcc.Graph(id='coverage-history')
        ]),
    ]),

    html.Div(className='row', style={'padding': '20px'}, children=[
        html.Div(className='twelve columns', children=[
            html.H3('Slowest Tests (Top 10)'),
            html.Table(id='slowest-tests-table', style={'width': '100%', 'borderCollapse': 'collapse'})
        ]),
    ]),

    dcc.Interval(
        id='interval-component',
        interval=5*1000, # Refresh every 5 seconds
        n_intervals=0
    )
])

@app.callback(
    [Output('coverage-indicator', 'children'),
     Output('tests-passed-indicator', 'children'),
     Output('test-time-indicator', 'children'),
     Output('slowest-tests-table', 'children')],
    [Input('interval-component', 'n_intervals')]
)
def update_metrics(n):
    total_tests, failures, errors, total_time, slowest_tests = parse_junit_report()
    line_rate, _, _ = parse_coverage_report()

    passed_tests = total_tests - (failures + errors)
    passed_percentage = (passed_tests / total_tests * 100) if total_tests > 0 else 0

    header = [html.Tr([html.Th("Test Name", style={'border': '1px solid #ddd', 'padding': '8px'}), html.Th("Time (s)", style={'border': '1px solid #ddd', 'padding': '8px'})], style={'backgroundColor': '#f2f2f2'})]
    rows = [html.Tr([html.Td(test['name'], style={'border': '1px solid #ddd', 'padding': '8px'}), html.Td(f"{test['time']:.4f}", style={'border': '1px solid #ddd', 'padding': '8px'})]) for test in slowest_tests]

    slowest_tests_table = header + rows

    return (
        f"{line_rate:.2f}%",
        f"{passed_tests} / {total_tests} ({passed_percentage:.2f}%)",
        f"{total_time:.2f}s",
        slowest_tests_table
    )

# For the history graph, we'd need to store data over time.
# This is a placeholder and would need a database in a real application.
@app.callback(
    Output('coverage-history', 'figure'),
    [Input('interval-component', 'n_intervals')]
)
def update_coverage_history(n):
    line_rate, _, _ = parse_coverage_report()

    # In a real app, you would append to a historical dataset here.
    # For now, we'll simulate a static history for demonstration.
    data_df = pd.DataFrame({
        'commit': ['abc', 'def', 'ghi', 'jkl', 'mno'],
        'coverage': [78.5, 80.2, 81.1, 80.5, line_rate]
    })

    figure = go.Figure(
        data=[go.Scatter(x=data_df['commit'], y=data_df['coverage'], mode='lines+markers', name='Coverage')],
        layout=go.Layout(
            title='Coverage History (Mock Data)',
            xaxis={'title': 'Commit Hash'},
            yaxis={'title': 'Line Coverage (%)', 'range': [0, 100]}
        )
    )
    return figure

if __name__ == '__main__':
    print("Starting test dashboard server on http://127.0.0.1:8050")
    app.run_server(debug=True)
